-- Cost Analysis Queries
-- Monitor AI Services and compute costs

-- AI Services credits per day (last 7 days)
SELECT 
    DATE_TRUNC('day', START_TIME) AS DATE,
    SUM(CREDITS_USED) AS CREDITS,
    SUM(CREDITS_USED) * 3 AS ESTIMATED_COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE SERVICE_TYPE = 'AI_SERVICES'
AND START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY 1 DESC;

-- AI Services credits per hour (last 24 hours)
SELECT 
    DATE_TRUNC('hour', START_TIME) AS HOUR,
    SUM(CREDITS_USED) AS CREDITS,
    SUM(CREDITS_USED) * 3 AS ESTIMATED_COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE SERVICE_TYPE = 'AI_SERVICES'
AND START_TIME >= DATEADD('day', -1, CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY 1 DESC;

-- Query history for parsing operations (timing and rows)
SELECT 
    QUERY_ID,
    TOTAL_ELAPSED_TIME/1000 AS SECONDS,
    TOTAL_ELAPSED_TIME/60000 AS MINUTES,
    ROWS_PRODUCED,
    CREDITS_USED_CLOUD_SERVICES,
    WAREHOUSE_SIZE,
    START_TIME
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY 
WHERE QUERY_TEXT LIKE 'INSERT INTO parsed_document%' 
ORDER BY START_TIME DESC 
LIMIT 10;

-- All service types cost breakdown (last 7 days)
SELECT 
    SERVICE_TYPE,
    SUM(CREDITS_USED) AS TOTAL_CREDITS,
    SUM(CREDITS_USED) * 3 AS ESTIMATED_COST_USD
FROM SNOWFLAKE.ACCOUNT_USAGE.METERING_HISTORY
WHERE START_TIME >= DATEADD('day', -7, CURRENT_TIMESTAMP())
GROUP BY 1
ORDER BY 2 DESC;

-- Cost per document parsed (estimate)
SELECT 
    COUNT(DISTINCT filename) AS DOCUMENTS_PARSED,
    COUNT(*) AS TOTAL_PAGES,
    34.8 AS AI_CREDITS_USED,  -- Update with actual value from metering history
    34.8 / COUNT(DISTINCT filename) AS CREDITS_PER_DOCUMENT,
    34.8 / COUNT(*) AS CREDITS_PER_PAGE,
    (34.8 * 3) / COUNT(DISTINCT filename) AS USD_PER_DOCUMENT,
    (34.8 * 3) / COUNT(*) AS USD_PER_PAGE
FROM GLD.PUBLIC.parsed_document;

